#!/bin/bash
set -e

echo "📱 Extracting for mobile platforms..."
echo ""
echo "✅ Web Version (Ready)"
echo "  - Framework: React + TypeScript + Vite"
echo "  - Build: npm run build"
echo "  - Output: dist/"
echo ""
echo "📦 To export for other platforms:"
echo ""
echo "React Native:"
echo "  npm install -g eas-cli"
echo "  eas init"
echo "  eas build"
echo ""
echo "PWA (Progressive Web App):"
echo "  - Already configured via manifest.json"
echo "  - Deploy dist/ folder to any web server"
echo ""
echo "Electron (Desktop):"
echo "  npm install --save-dev electron"
echo "  npm install --dev electron-builder"
echo ""
echo "Tauri (Desktop - Rust + Web):"
echo "  cargo install tauri-cli"
echo "  cargo tauri init"
echo ""
